spring.application.name=trvelplannerplatform-backend
spring.datasource.url=jdbc:mysql://localhost:3306/travel_planner
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
registration.enabled=true
logging.level.org.springframework.security=trace

jwt.secret=MyVeryStrongSecretKeyForTravelPlannerApplication12345678901234567890
jwt.expiration=3600000